#!/bin/sh

#/***************************************************************************
# *   copyright            : (C) 2011 by Karel Vesely,UPGM,FIT,VUT,Brno     *
# *   email                : iveselyk@fit.vutbr.cz                          *
# ***************************************************************************
# *                                                                         *
# *   This program is free software; you can redistribute it and/or modify  *
# *   it under the terms of the APACHE License as published by the          *
# *   Apache Software Foundation; either version 2.0 of the License,        *
# *   or (at your option) any later version.                                *
# *                                                                         *
# ***************************************************************************/

# generates gmmbypass to use with HTK decoder on posterior features

if [ $# != 2 ]; then 
  echo "$0 dict(i) hmmdefs_file(o)"; exit 1;
fi

dict=$1
hmmdefs_file=$2

C=1.0

##########################################################
#make hmmdefs

#number of phonemes
num_phn=`wc $dict | awk '{print $1}'`

zero=""
for((i=0;$i<$num_phn;i++));do
  zero="$zero 0"
done


echo " ~o <VecSize> $num_phn <USER> " > $hmmdefs_file

count=0;
for phn in `cat $dict`; do
  tmp=""
  for((i=0;$i<$num_phn;i++));do
    if [ $i -eq $count ]; then
      tmp="$tmp $C"
    else
      tmp="$tmp 1e30"
    fi
  done
  count=$((count + 1))

    echo "~s \"$phn\"
    <Mean> $num_phn
      $zero
    <Variance> $num_phn
      $tmp 
    <GConst> 0">> $hmmdefs_file

done


for phn in `cat $dict | sed 's/\(.*\)__[0-9]/\1/'|sort|uniq`; do
echo "~h \"$phn\"
 <BeginHMM>
   <NumStates> 150
   <State> 2 ~s \"${phn}\"
   <State> 3 ~s \"${phn}\"
   <State> 4 ~s \"${phn}\"
   <State> 5 ~s \"${phn}\"
   <State> 6 ~s \"${phn}\"
   <State> 7 ~s \"${phn}\"
   <State> 8 ~s \"${phn}\"
   <State> 9 ~s \"${phn}\"
   <State> 10 ~s \"${phn}\"
   <State> 11 ~s \"${phn}\"
   <State> 12 ~s \"${phn}\"
   <State> 13 ~s \"${phn}\"
   <State> 14 ~s \"${phn}\"
   <State> 15 ~s \"${phn}\"
   <State> 16 ~s \"${phn}\"
   <State> 17 ~s \"${phn}\"
   <State> 18 ~s \"${phn}\"
   <State> 19 ~s \"${phn}\"
   <State> 20 ~s \"${phn}\"
   <State> 21 ~s \"${phn}\"
   <State> 22 ~s \"${phn}\"
   <State> 23 ~s \"${phn}\"
   <State> 24 ~s \"${phn}\"
   <State> 25 ~s \"${phn}\"
   <State> 26 ~s \"${phn}\"
   <State> 27 ~s \"${phn}\"
   <State> 28 ~s \"${phn}\"
   <State> 29 ~s \"${phn}\"
   <State> 30 ~s \"${phn}\"
   <State> 31 ~s \"${phn}\"
   <State> 32 ~s \"${phn}\"
   <State> 33 ~s \"${phn}\"
   <State> 34 ~s \"${phn}\"
   <State> 35 ~s \"${phn}\"
   <State> 36 ~s \"${phn}\"
   <State> 37 ~s \"${phn}\"
   <State> 38 ~s \"${phn}\"
   <State> 39 ~s \"${phn}\"
   <State> 40 ~s \"${phn}\"
   <State> 41 ~s \"${phn}\"
   <State> 42 ~s \"${phn}\"
   <State> 43 ~s \"${phn}\"
   <State> 44 ~s \"${phn}\"
   <State> 45 ~s \"${phn}\"
   <State> 46 ~s \"${phn}\"
   <State> 47 ~s \"${phn}\"
   <State> 48 ~s \"${phn}\"
   <State> 49 ~s \"${phn}\"
   <State> 50 ~s \"${phn}\"
   <State> 51 ~s \"${phn}\"
   <State> 52 ~s \"${phn}\"
   <State> 53 ~s \"${phn}\"
   <State> 54 ~s \"${phn}\"
   <State> 55 ~s \"${phn}\"
   <State> 56 ~s \"${phn}\"
   <State> 57 ~s \"${phn}\"
   <State> 58 ~s \"${phn}\"
   <State> 59 ~s \"${phn}\"
   <State> 60 ~s \"${phn}\"
   <State> 61 ~s \"${phn}\"
   <State> 62 ~s \"${phn}\"
   <State> 63 ~s \"${phn}\"
   <State> 64 ~s \"${phn}\"
   <State> 65 ~s \"${phn}\"
   <State> 66 ~s \"${phn}\"
   <State> 67 ~s \"${phn}\"
   <State> 68 ~s \"${phn}\"
   <State> 69 ~s \"${phn}\"
   <State> 70 ~s \"${phn}\"
   <State> 71 ~s \"${phn}\"
   <State> 72 ~s \"${phn}\"
   <State> 73 ~s \"${phn}\"
   <State> 74 ~s \"${phn}\"
   <State> 75 ~s \"${phn}\"
   <State> 76 ~s \"${phn}\"
   <State> 77 ~s \"${phn}\"
   <State> 78 ~s \"${phn}\"
   <State> 79 ~s \"${phn}\"
   <State> 80 ~s \"${phn}\"
   <State> 81 ~s \"${phn}\"
   <State> 82 ~s \"${phn}\"
   <State> 83 ~s \"${phn}\"
   <State> 84 ~s \"${phn}\"
   <State> 85 ~s \"${phn}\"
   <State> 86 ~s \"${phn}\"
   <State> 87 ~s \"${phn}\"
   <State> 88 ~s \"${phn}\"
   <State> 89 ~s \"${phn}\"
   <State> 90 ~s \"${phn}\"
   <State> 91 ~s \"${phn}\"
   <State> 92 ~s \"${phn}\"
   <State> 93 ~s \"${phn}\"
   <State> 94 ~s \"${phn}\"
   <State> 95 ~s \"${phn}\"
   <State> 96 ~s \"${phn}\"
   <State> 97 ~s \"${phn}\"
   <State> 98 ~s \"${phn}\"
   <State> 99 ~s \"${phn}\"
   <State> 100 ~s \"${phn}\"
   <State> 101 ~s \"${phn}\"
   <State> 102 ~s \"${phn}\"
   <State> 103 ~s \"${phn}\"
   <State> 104 ~s \"${phn}\"
   <State> 105 ~s \"${phn}\"
   <State> 106 ~s \"${phn}\"
   <State> 107 ~s \"${phn}\"
   <State> 108 ~s \"${phn}\"
   <State> 109 ~s \"${phn}\"
   <State> 110 ~s \"${phn}\"
   <State> 111 ~s \"${phn}\"
   <State> 112 ~s \"${phn}\"
   <State> 113 ~s \"${phn}\"
   <State> 114 ~s \"${phn}\"
   <State> 115 ~s \"${phn}\"
   <State> 116 ~s \"${phn}\"
   <State> 117 ~s \"${phn}\"
   <State> 118 ~s \"${phn}\"
   <State> 119 ~s \"${phn}\"
   <State> 120 ~s \"${phn}\"
   <State> 121 ~s \"${phn}\"
   <State> 122 ~s \"${phn}\"
   <State> 123 ~s \"${phn}\"
   <State> 124 ~s \"${phn}\"
   <State> 125 ~s \"${phn}\"
   <State> 126 ~s \"${phn}\"
   <State> 127 ~s \"${phn}\"
   <State> 128 ~s \"${phn}\"
   <State> 129 ~s \"${phn}\"
   <State> 130 ~s \"${phn}\"
   <State> 131 ~s \"${phn}\"
   <State> 132 ~s \"${phn}\"
   <State> 133 ~s \"${phn}\"
   <State> 134 ~s \"${phn}\"
   <State> 135 ~s \"${phn}\"
   <State> 136 ~s \"${phn}\"
   <State> 137 ~s \"${phn}\"
   <State> 138 ~s \"${phn}\"
   <State> 139 ~s \"${phn}\"
   <State> 140 ~s \"${phn}\"
   <State> 141 ~s \"${phn}\"
   <State> 142 ~s \"${phn}\"
   <State> 143 ~s \"${phn}\"
   <State> 144 ~s \"${phn}\"
   <State> 145 ~s \"${phn}\"
   <State> 146 ~s \"${phn}\"
   <State> 147 ~s \"${phn}\"
   <State> 148 ~s \"${phn}\"
   <State> 149 ~s \"${phn}\"   
   <TransP> 150
